/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "fb303_constants.h"

namespace facebook { namespace fb303 {

const fb303Constants g_fb303_constants;

fb303Constants::fb303Constants() {
}

}} // namespace

